"""Unit test for company name resolution & cleaning in Tagesschau news scan."""

import pytest
from core.utils import clean_company_name_candidates
from tests.helpers import api_client


def test_clean_company_name_candidates_legal_forms_and_clauses():
    """Verify that candidate generation strips legal form extensions and representation clauses."""
    cands1 = clean_company_name_candidates("Flughafen München GmbH")
    assert "Flughafen München" in cands1

    cands2 = clean_company_name_candidates("Flughafen München GmbH & Co. KG")
    assert "Flughafen München" in cands2

    cands3 = clean_company_name_candidates(
        "Bundesrepublik Deutschland, vertreten durch das Bundesministerium des Innern, "
        "vertreten durch das Beschaffungsamt des BMI"
    )
    assert "Bundesrepublik Deutschland" in cands3

    cands4 = clean_company_name_candidates("Stadtwerke München GmbH")
    assert "Stadtwerke München" in cands4

    cands6 = clean_company_name_candidates("MHP Management- und IT-Beratung GmbH")
    assert "MHP Management- und IT-Beratung GmbH" in cands6
    assert "MHP Management- und IT-Beratung" in cands6
    assert "MHP Management" in cands6
    assert "MHP" in cands6


@pytest.mark.asyncio
async def test_flughafen_muenchen_gmbh_tagesschau_news_scan():
    """Verify that company summary extraction for 'Flughafen München GmbH' populates Tagesschau news scan."""
    async with api_client() as client:
        bid_id = "bid-flughafen-muenchen-001"
        company_name = "Flughafen München GmbH"

        res = await client.post(
            f"/bids/{bid_id}/company-summary/extract",
            json={"company_name": company_name}
        )
        assert res.status_code == 200
        data = res.json()

        news_scan = data.get("tagesschau_news_scan", {})
        assert news_scan.get("articles_found", 0) > 0
        headlines = news_scan.get("recent_headlines", [])
        assert len(headlines) > 0


@pytest.mark.asyncio
async def test_bundesrepublik_deutschland_vertreten_durch_tagesschau_news_scan():
    """Verify that company summary extraction for long official name populates Tagesschau news scan."""
    async with api_client() as client:
        bid_id = "bid-bundesrepublik-001"
        company_name = "Bundesrepublik Deutschland, vertreten durch das Bundesministerium des Innern, vertreten durch das Beschaffungsamt des BMI"

        res = await client.post(
            f"/bids/{bid_id}/company-summary/extract",
            json={"company_name": company_name}
        )
        assert res.status_code == 200
        data = res.json()

        news_scan = data.get("tagesschau_news_scan", {})
        assert news_scan.get("articles_found", 0) > 0


def test_right_to_left_word_reduction_sequence():
    """Verify that candidates are generated by popping the last word from right to left."""
    cands = clean_company_name_candidates("MHP Management- und IT-Beratung GmbH")
    assert cands[0] == "MHP Management- und IT-Beratung GmbH"
    assert cands[1] == "MHP Management- und IT-Beratung"
    assert "MHP Management" in cands
    assert "MHP" in cands
    assert cands[-1] == "MHP"


@pytest.mark.asyncio
async def test_tagesschau_early_stop_on_first_matching_term(mocker):
    """Verify that search stops immediately when articles are found for a longer query candidate."""
    from api.v1.company_summary import run_stage2_market_and_news

    queried_terms = []

    class MockResponse:
        def __init__(self, status_code, json_data):
            self.status_code = status_code
            self._json = json_data

        def json(self):
            return self._json

    async def mock_get(url, params=None, timeout=10.0):
        term = params.get("searchText", "") if params else ""
        queried_terms.append(term)
        if term == "MHP Management- und IT-Beratung":
            return MockResponse(
                200,
                {
                    "searchResults": [
                        {
                            "title": "MHP Management- und IT-Beratung wächst stark",
                            "firstSentence": "MHP erzielt neues Rekordwachstum.",
                            "detailsweb": "https://www.tagesschau.de/wirtschaft/mhp-100.html",
                            "date": "2026-05-10",
                        }
                    ]
                },
            )
        return MockResponse(200, {"searchResults": []})

    mocker.patch("httpx.AsyncClient.get", side_effect=mock_get)
    mocker.patch(
        "api.v1.company_summary.score_articles_with_ai",
        side_effect=lambda articles, name, db=None: [
            a.update({"is_relevant": True, "sentiment_score": 80}) for a in articles
        ],
    )

    res = await run_stage2_market_and_news("MHP Management- und IT-Beratung GmbH")
    assert res["tagesschau_news_scan"]["articles_found"] == 1
    assert "MHP Management- und IT-Beratung GmbH" in queried_terms
    assert "MHP Management- und IT-Beratung" in queried_terms
    assert "MHP Management" not in queried_terms
    assert "MHP" not in queried_terms
